-- Create blacklist table
create table if not exists blacklist (
    id bigint primary key generated by default as identity,
    phone text,
    name text,
    reason text,
    created_at timestamptz default now(),
    created_by text
);

-- Enable RLS
alter table blacklist enable row level security;

-- Policies (Allow public read for checking, authenticated write)
create policy "Public Read Blacklist" on blacklist for select using (true);
create policy "Authenticated Insert Blacklist" on blacklist for insert with check (auth.role() = 'authenticated');
create policy "Authenticated Update Blacklist" on blacklist for update using (auth.role() = 'authenticated');
create policy "Authenticated Delete Blacklist" on blacklist for delete using (auth.role() = 'authenticated');

-- Indexes for faster lookup
create index if not exists idx_blacklist_phone on blacklist(phone);
create index if not exists idx_blacklist_name on blacklist(name);

-- Seed sample data
insert into blacklist (phone, name, reason)
select '0987654321', 'Nguyễn Văn Bom', 'Hay bom hàng'
where not exists (select 1 from blacklist where phone = '0987654321');

insert into blacklist (phone, name, reason)
select '0912345678', 'Trần Văn Spam', 'Spam đơn ảo'
where not exists (select 1 from blacklist where phone = '0912345678');
