-- 1. Roles Definition (Vị trí/Bộ phận)
CREATE TABLE IF NOT EXISTS app_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT UNIQUE NOT NULL, -- e.g., 'MKT_LEADER', 'SALE_STAFF'
    name TEXT NOT NULL, -- e.g., 'Trưởng nhóm Marketing', 'Nhân viên Sale'
    department TEXT, -- e.g., 'Marketing', 'Sales', 'R&D'
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. User Role Assignment (Phân quyền Nhân viên)
CREATE TABLE IF NOT EXISTS app_user_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL, -- Link to Firebase User by Email
    role_code TEXT REFERENCES app_roles(code) ON DELETE SET NULL,
    assigned_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    assigned_by TEXT
);

-- 3. Detailed Permissions (Phân quyền Module & Cột)
CREATE TABLE IF NOT EXISTS app_permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_code TEXT REFERENCES app_roles(code) ON DELETE CASCADE,
    resource_code TEXT NOT NULL, -- e.g., 'MODULE_RND', 'MODULE_SALE'
    
    -- Permissions Flags
    can_view BOOLEAN DEFAULT FALSE,
    can_edit BOOLEAN DEFAULT FALSE,
    can_delete BOOLEAN DEFAULT FALSE,
    
    -- Column Level Security (JSON Array of allowed columns, or ["*"] for all)
    allowed_columns JSONB DEFAULT '["*"]'::jsonb,
    
    -- Constraint: One permission config per Role per Resource
    UNIQUE(role_code, resource_code)
);

-- 4. Seed Data (Dữ liệu mẫu)
INSERT INTO app_roles (code, name, department, description) VALUES
('ADMIN', 'Quản trị viên', 'Board', 'Toàn quyền hệ thống'),
('DIRECTOR', 'Giám đốc', 'Board', 'Xem tất cả báo cáo'),
('MKT_LEADER', 'Trưởng nhóm MKT', 'Marketing', 'Quản lý MKT'),
('SALE_MEMBER', 'Nhân viên Sale', 'Sales', 'Chỉ xem đơn của mình')
ON CONFLICT (code) DO NOTHING;

-- Grant Admin full access
INSERT INTO app_permissions (role_code, resource_code, can_view, can_edit, can_delete, allowed_columns) VALUES
('ADMIN', 'ALL', TRUE, TRUE, TRUE, '["*"]')
ON CONFLICT DO NOTHING;
