-- Create exchange_rates table
create table if not exists exchange_rates (
    id int primary key generated by default as identity,
    rate_name text default 'Standard',
    usd numeric default 25500,
    cad numeric default 18000,
    aud numeric default 16500,
    jpy numeric default 170,
    krw numeric default 18,
    gbp numeric default 32000,
    vnd numeric default 1,
    last_updated_by text,
    updated_at timestamptz default now()
);

-- Enable RLS
alter table exchange_rates enable row level security;
create policy "Public Read" on exchange_rates for select using (true);
create policy "Public Update" on exchange_rates for update using (true) with check (true);
create policy "Public Insert" on exchange_rates for insert with check (true);

-- Seed initial row if not exists
insert into exchange_rates (id, usd, cad, aud, jpy, krw, gbp)
select 1, 26077, 18884, 17315, 168, 17.9, 32000
where not exists (select 1 from exchange_rates where id = 1);
