-- Ensure system_settings exists and has required columns for Admin Tools.

CREATE TABLE IF NOT EXISTS public.system_settings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  type text NOT NULL DEFAULT 'normal',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  updated_by text
);

ALTER TABLE public.system_settings
  ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now(),
  ADD COLUMN IF NOT EXISTS updated_by text,
  ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now(),
  ADD COLUMN IF NOT EXISTS name text,
  ADD COLUMN IF NOT EXISTS type text;

UPDATE public.system_settings
SET type = 'normal'
WHERE type IS NULL;

CREATE INDEX IF NOT EXISTS idx_system_settings_updated_at
  ON public.system_settings (updated_at);

CREATE INDEX IF NOT EXISTS idx_system_settings_name
  ON public.system_settings (name);

ALTER TABLE public.system_settings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow all access to system_settings" ON public.system_settings;
CREATE POLICY "Allow all access to system_settings"
  ON public.system_settings
  FOR ALL
  TO authenticated, anon
  USING (true)
  WITH CHECK (true);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.system_settings TO authenticated, anon;

DO $$
BEGIN
  IF to_regclass('public.system_settings_id_seq') IS NOT NULL THEN
    GRANT USAGE, SELECT ON SEQUENCE public.system_settings_id_seq TO authenticated, anon;
  END IF;
END $$;
