-- Lịch sử bật/tắt trạng thái U1 trên danh_sach_van_don

CREATE TABLE IF NOT EXISTS public.danh_sach_van_don_u1_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  danh_sach_van_don_id bigint,
  ho_va_ten text NOT NULL,
  chi_nhanh text,
  trang_thai_cu text,
  trang_thai_moi text,
  hanh_dong text NOT NULL,
  changed_by text,
  changed_at timestamptz NOT NULL DEFAULT now(),
  ghi_chu text
);

CREATE INDEX IF NOT EXISTS idx_dsvd_u1_history_changed_at
  ON public.danh_sach_van_don_u1_history (changed_at DESC);

CREATE INDEX IF NOT EXISTS idx_dsvd_u1_history_ho_va_ten
  ON public.danh_sach_van_don_u1_history (ho_va_ten);

CREATE INDEX IF NOT EXISTS idx_dsvd_u1_history_chi_nhanh
  ON public.danh_sach_van_don_u1_history (chi_nhanh);

CREATE INDEX IF NOT EXISTS idx_dsvd_u1_history_record_id
  ON public.danh_sach_van_don_u1_history (danh_sach_van_don_id);

ALTER TABLE public.danh_sach_van_don_u1_history ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow all access to danh_sach_van_don_u1_history" ON public.danh_sach_van_don_u1_history;
CREATE POLICY "Allow all access to danh_sach_van_don_u1_history"
  ON public.danh_sach_van_don_u1_history
  FOR ALL
  TO anon, authenticated
  USING (true)
  WITH CHECK (true);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.danh_sach_van_don_u1_history TO anon, authenticated;
