-- Create exchange_rates table for currency conversion management.

CREATE TABLE IF NOT EXISTS public.exchange_rates (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ti_gia text NOT NULL,
  gia_tri numeric(12,2) NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_exchange_rates_ti_gia_unique
  ON public.exchange_rates (ti_gia);

CREATE INDEX IF NOT EXISTS idx_exchange_rates_ti_gia
  ON public.exchange_rates (ti_gia);

CREATE OR REPLACE FUNCTION public.update_exchange_rates_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trigger_update_exchange_rates_updated_at ON public.exchange_rates;
CREATE TRIGGER trigger_update_exchange_rates_updated_at
  BEFORE UPDATE ON public.exchange_rates
  FOR EACH ROW
  EXECUTE FUNCTION public.update_exchange_rates_updated_at();

INSERT INTO public.exchange_rates (ti_gia, gia_tri)
VALUES
  ('USD', 25000),
  ('JPY', 180),
  ('CAD', 19000),
  ('AUD', 18000),
  ('GBP', 32000),
  ('KRW', 20)
ON CONFLICT (ti_gia)
DO UPDATE SET gia_tri = EXCLUDED.gia_tri;

ALTER TABLE public.exchange_rates ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow all access to exchange_rates" ON public.exchange_rates;
CREATE POLICY "Allow all access to exchange_rates"
  ON public.exchange_rates
  FOR ALL
  TO authenticated, anon
  USING (true)
  WITH CHECK (true);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.exchange_rates TO authenticated, anon;
GRANT USAGE, SELECT ON SEQUENCE public.exchange_rates_id_seq TO authenticated, anon;
