-- Create danh_sach_van_don table used by DanhSachVanDon / chiaDonVanDon / RBAC helper.
-- Idempotent migration.

CREATE TABLE IF NOT EXISTS public.danh_sach_van_don (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ho_va_ten text NOT NULL,
  trang_thai_chia text,
  chi_nhanh text,
  so_don integer NOT NULL DEFAULT 0,
  nguoi_sua_ho jsonb NOT NULL DEFAULT '[]'::jsonb,
  nguoi_day_ffm jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT danh_sach_van_don_nguoi_sua_ho_is_array CHECK (jsonb_typeof(nguoi_sua_ho) = 'array'),
  CONSTRAINT danh_sach_van_don_nguoi_day_ffm_is_array CHECK (jsonb_typeof(nguoi_day_ffm) = 'array')
);

ALTER TABLE public.danh_sach_van_don
  ADD COLUMN IF NOT EXISTS ho_va_ten text,
  ADD COLUMN IF NOT EXISTS trang_thai_chia text,
  ADD COLUMN IF NOT EXISTS chi_nhanh text,
  ADD COLUMN IF NOT EXISTS so_don integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS nguoi_sua_ho jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS nguoi_day_ffm jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now(),
  ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();

UPDATE public.danh_sach_van_don
SET
  so_don = COALESCE(so_don, 0),
  nguoi_sua_ho = COALESCE(nguoi_sua_ho, '[]'::jsonb),
  nguoi_day_ffm = COALESCE(nguoi_day_ffm, '[]'::jsonb),
  created_at = COALESCE(created_at, now()),
  updated_at = COALESCE(updated_at, now())
WHERE true;

CREATE UNIQUE INDEX IF NOT EXISTS idx_danh_sach_van_don_ho_va_ten_unique
  ON public.danh_sach_van_don (ho_va_ten);

CREATE INDEX IF NOT EXISTS idx_danh_sach_van_don_chi_nhanh
  ON public.danh_sach_van_don (chi_nhanh);

CREATE INDEX IF NOT EXISTS idx_danh_sach_van_don_trang_thai_chia
  ON public.danh_sach_van_don (trang_thai_chia);

CREATE OR REPLACE FUNCTION public.update_danh_sach_van_don_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trigger_update_danh_sach_van_don_updated_at ON public.danh_sach_van_don;
CREATE TRIGGER trigger_update_danh_sach_van_don_updated_at
  BEFORE UPDATE ON public.danh_sach_van_don
  FOR EACH ROW
  EXECUTE FUNCTION public.update_danh_sach_van_don_updated_at();

ALTER TABLE public.danh_sach_van_don ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow all access to danh_sach_van_don" ON public.danh_sach_van_don;
CREATE POLICY "Allow all access to danh_sach_van_don"
  ON public.danh_sach_van_don
  FOR ALL
  TO anon, authenticated
  USING (true)
  WITH CHECK (true);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.danh_sach_van_don TO anon, authenticated;
